 const Alpha = [
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 3, selection: 0},
  {team: 2, phase: 3, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
];

const Beta = [
  {team: 1, phase: 3, selection: 0},
  {team: 2, phase: 3, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
];

const Gamma = [
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
];

const Delta = [
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0}, 
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
];

const Epsilon = [
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 1, phase: 3, selection: 0},
  {team: 2, phase: 3, selection: 0},
];

const Zeta = [
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 1, selection: 0},
  {team: 1, phase: 2, selection: 0},
  {team: 2, phase: 1, selection: 0},
  {team: 2, phase: 2, selection: 0},
  {team: 1, phase: 1, selection: 0},
];

export { Alpha, Beta, Gamma, Delta, Epsilon, Zeta };
