 const Alpha = [
  {i: 0, team: 0, phase: 2, selection: 0},
  {i: 1, team: 1, phase: 2, selection: 0},
  {i: 2, team: 0, phase: 2, selection: 0},
  {i: 3, team: 1, phase: 2, selection: 0},
  {i: 4, team: 0, phase: 1, selection: 0},
  {i: 5, team: 1, phase: 1, selection: 0},
  {i: 6, team: 1, phase: 1, selection: 0},
  {i: 7, team: 0, phase: 1, selection: 0},
  {i: 8, team: 0, phase: 2, selection: 0},
  {i: 9, team: 1, phase: 2, selection: 0},
  {i: 10, team: 0, phase: 3, selection: 0},
  {i: 11, team: 1, phase: 3, selection: 0},
  {i: 12, team: 0, phase: 2, selection: 0},
  {i: 13, team: 1, phase: 2, selection: 0},
  {i: 14, team: 0, phase: 2, selection: 0},
  {i: 15, team: 1, phase: 2, selection: 0},
  {i: 16, team: 1, phase: 1, selection: 0},
  {i: 17, team: 0, phase: 1, selection: 0},
  {i: 18, team: 1, phase: 1, selection: 0},
  {i: 19, team: 0, phase: 1, selection: 0},
  {i: 20, team: 0, phase: 2, selection: 0},
  {i: 21, team: 1, phase: 2, selection: 0},
  {i: 22, team: 0, phase: 2, selection: 0},
  {i: 23, team: 1, phase: 2, selection: 0},
  {i: 24, team: 0, phase: 1, selection: 0},
  {i: 25, team: 1, phase: 1, selection: 0},
];

const Beta = [
  {i: 0, team: 0, phase: 3, selection: 0},
  {i: 1, team: 1, phase: 3, selection: 0},
  {i: 2, team: 0, phase: 2, selection: 0},
  {i: 3, team: 1, phase: 2, selection: 0},
  {i: 4, team: 0, phase: 2, selection: 0},
  {i: 5, team: 1, phase: 2, selection: 0},
  {i: 6, team: 0, phase: 2, selection: 0},
  {i: 7, team: 1, phase: 2, selection: 0},
  {i: 8, team: 0, phase: 1, selection: 0},
  {i: 9, team: 1, phase: 1, selection: 0},
  {i: 10, team: 1, phase: 1, selection: 0},
  {i: 11, team: 0, phase: 1, selection: 0},
  {i: 12, team: 0, phase: 1, selection: 0},
  {i: 13, team: 1, phase: 1, selection: 0},
  {i: 14, team: 1, phase: 1, selection: 0},
  {i: 15, team: 0, phase: 1, selection: 0},
  {i: 16, team: 0, phase: 1, selection: 0},
  {i: 17, team: 1, phase: 1, selection: 0},
];

const Gamma = [
  {i: 0, team: 0, phase: 2, selection: 0},
  {i: 1, team: 1, phase: 2, selection: 0},
  {i: 2, team: 0, phase: 1, selection: 0},
  {i: 3, team: 1, phase: 1, selection: 0},
  {i: 4, team: 1, phase: 1, selection: 0},
  {i: 5, team: 0, phase: 1, selection: 0},
  {i: 6, team: 0, phase: 1, selection: 0},
  {i: 7, team: 1, phase: 1, selection: 0},
  {i: 8, team: 1, phase: 1, selection: 0},
  {i: 9, team: 0, phase: 1, selection: 0},
  {i: 10, team: 0, phase: 1, selection: 0},
  {i: 11, team: 1, phase: 1, selection: 0},
];

const Delta = [
  {i: 0, team: 0, phase: 2, selection: 0},
  {i: 1, team: 1, phase: 2, selection: 0},
  {i: 2, team: 0, phase: 1, selection: 0},
  {i: 3, team: 1, phase: 1, selection: 0},
  {i: 4, team: 0, phase: 1, selection: 0},
  {i: 5, team: 1, phase: 1, selection: 0},
  {i: 6, team: 0, phase: 1, selection: 0}, 
  {i: 7, team: 0, phase: 2, selection: 0},
  {i: 8, team: 1, phase: 2, selection: 0},
  {i: 9, team: 1, phase: 1, selection: 0},
  {i: 10, team: 0, phase: 1, selection: 0},
  {i: 11, team: 1, phase: 1, selection: 0},
  {i: 12, team: 0, phase: 1, selection: 0},
  {i: 13, team: 1, phase: 1, selection: 0},
];

const Epsilon = [
  {i: 0, team: 0, phase: 2, selection: 0},
  {i: 1, team: 1, phase: 2, selection: 0},
  {i: 2, team: 0, phase: 1, selection: 0},
  {i: 3, team: 1, phase: 1, selection: 0},
  {i: 4, team: 0, phase: 1, selection: 0},
  {i: 5, team: 1, phase: 1, selection: 0},
  {i: 6, team: 0, phase: 1, selection: 0},
  {i: 7, team: 1, phase: 1, selection: 0},
  {i: 8, team: 0, phase: 1, selection: 0},
  {i: 9, team: 1, phase: 1, selection: 0},
  {i: 10, team: 0, phase: 1, selection: 0},
  {i: 11, team: 1, phase: 1, selection: 0},
  {i: 12, team: 0, phase: 3, selection: 0},
  {i: 13, team: 1, phase: 3, selection: 0},
];

const Zeta = [
  {i: 0, team: 0, phase: 2, selection: 0},
  {i: 1, team: 1, phase: 1, selection: 0},
  {i: 2, team: 1, phase: 2, selection: 0},
  {i: 3, team: 0, phase: 1, selection: 0},
  {i: 4, team: 0, phase: 2, selection: 0},
  {i: 5, team: 1, phase: 1, selection: 0},
  {i: 6, team: 1, phase: 2, selection: 0},
  {i: 7, team: 0, phase: 1, selection: 0},
  {i: 8, team: 0, phase: 2, selection: 0},
  {i: 9, team: 1, phase: 1, selection: 0},
  {i: 10, team: 1, phase: 2, selection: 0},
  {i: 11, team: 0, phase: 1, selection: 0},
  {i: 12, team: 0, phase: 2, selection: 0},
  {i: 13, team: 1, phase: 1, selection: 0},
  {i: 14, team: 1, phase: 2, selection: 0},
  {i: 15, team: 0, phase: 1, selection: 0},
  {i: 16, team: 0, phase: 2, selection: 0},
  {i: 17, team: 1, phase: 1, selection: 0},
  {i: 18, team: 1, phase: 2, selection: 0},
  {i: 19, team: 0, phase: 1, selection: 0},
];

export { Alpha, Beta, Gamma, Delta, Epsilon, Zeta };
